### ISSUE TITLE
Install and run embase

### ISSUE THREAD

**Issue by Giwrgosyea** [5g-empower/empower-embase#1]
Hello, 
I followed your instructions for downloading the dependencies and running embase.
But ./embase --id 1 in empower-embase/sim/lte reports :  log_init                 : Could not open the log file!
Any advice ?

G.

I solved this with running with sudo

**Comment by Giwrgosyea** [comment]
Beside that any documentation on how the console works?

**Comment by kewinrausch** [comment]
Hi there,
actually there is little/no documentation for this project, but you can follow the upper/lower bar if you are interested in the possible commands that can be issued at the application.

At the starting screen, you can type 'a', for example, to add an UE, and move through the field of the mask by using the arrow keys. Enter will order to create an UE with the given fields.

If you have any more specific question you can write then in the mailing list. In the mean time, I'll try to provide a basic "HowTo" use it somewhere, with a practical example with the EmPOWER controller.
